### ISSUE TITLE
About RegEx issue

### ISSUE THREAD

**Issue by SMooxx** [rsnitsch/py3createtorrent#10]
When I want to use the -e option to exclude specific file types like rar, r00, r01, r02,... r99, etc. 

` -exclude-pattern '^.*\.r.*$'`

> ![image](https://user-images.githubusercontent.com/9960618/110289200-0c642600-8024-11eb-9f12-96483695abd3.png)

It gives such error. 
![image](https://user-images.githubusercontent.com/9960618/110288943-af687000-8023-11eb-8bda-508431e4eeff.png)

But this RegEx is OK with the following command,  
**`ls |grep -E '^.*\.r.*$'`**
So I am wondering if py3createtorrent only support RegEx formats in your examples, like **"(jpg|JPG)$"** only?

**Comment by rsnitsch** [comment]
Try again with ``--exclude-pattern`` (double dash) instead of ``-exclude-pattern``. Python uses single dash for short switches (for example ``-h``) or double dash for long switches (for example ``--help``).

**Comment by moerfutin** [comment]
> Try again with `--exclude-pattern` (double dash) instead of `-exclude-pattern`. Python uses single dash for short switches (for example `-h`) or double dash for long switches (for example `--help`).

Thanks. the following command works. Much appreciated.
`--exclude-pattern "(^.*\.r.*|sfv)$"`

Another issue here. I used to use mktorrent which can support ‘relative path'.
But it seems py3createtorrent can't support 'relative path' here. For example, If I use it like this, 
`py3createtorrent -v -p 8192 -P -s FL -o ~/example.torrent -d -1 -t  https://tracker/announce.php --exclude-pattern "(^.*\.r.*|sfv)$" ./` 
It will create a torrent with a wierd name **[. ]** in its **name** field, and I can't add this torrent to my torrent client anyway.
![image](https://user-images.githubusercontent.com/9960618/110303654-9799e780-8035-11eb-975e-12f10bd592b0.png)

If I change the path to full path, the torrent created will be OK.
