### ISSUE TITLE
Support for usage as a module

### ISSUE THREAD

**Issue by gs11** [rsnitsch/py3createtorrent#13]
py3createtorrent can as of now only be used as a CLI tool but it'd be super useful if it exposed methods to use from other python modules.

**Comment by ToasterUwU** [comment]
+1 for this. I still use it now but in the scuffed way of using it as a CLI tool within my Python script.

**Comment by ToasterUwU** [comment]
Note to self: If there is no positiv response to this in a few weeks, make it yourself.

**Comment by ToasterUwU** [comment]
@rsnitsch If i make a PR for this and do all the work for you, would you merge it?

**Comment by ToasterUwU** [comment]
Cool, i will make 2 PRs then. One for some github workflow things ( Dependabot, and Linting checks ), and then the feature PR

**Comment by rsnitsch** [comment]
Cool 👌

**Comment by fakerybakery** [comment]
Hi, if this is merged would you consider switching from GPL to LGPL? Thank yoU!

**Comment by rsnitsch** [comment]
@fakerybakery We switched to LGPL and just published the new version with @ToasterUwU's contribution that allows for usage as a module: https://github.com/rsnitsch/py3createtorrent/releases/tag/v1.2.0
