### ISSUE TITLE
Make "master" the default branch again

### ISSUE THREAD

**Issue by ToasterUwU** [rsnitsch/py3createtorrent#15]
IDK why you made the "develop" branch the default, but that's not really good.
It's confusing to have a "master" branch, but it not being the master branch.

I suggest you make a PR to merge all the stuff from develop into master, and then change the default back to master. For the sake of following the standard and not confusing people.

I would do it myself, but to make a PR for two branches of your repo, I would need to be a collaborator.

@rsnitsch

**Comment by ToasterUwU** [comment]
i will wait for a response/action from you, before I make PRs for the other stuff mentioned in #13

**Comment by rsnitsch** [comment]
It is not correct that the `master` branch always has to be the "default" branch (default as in "for active development, including pull requests"). There is more than one standard/convention.

In this project, as in many others, I am adhering to the [Git-flow concept](https://danielkummer.github.io/git-flow-cheatsheet/index.html). This means the `master` branch is only touched when making a new release. All development, including pull requests, is conducted on the `develop` branch or, optionally, in `feature/xyz` branches (which are based on the `develop` branch also and then merged back into `develop` when done). It's a fairly popular method.

**Comment by ToasterUwU** [comment]
Never heard of it, never seen it in the wild, and don't really like it either.

I know there isn't "one way and no other way" to do it, but having master as the default branch is by far the biggest standard. Not saying "Change it, you are wrong", just that it is the standard, and that's why I assumed that was a misclick from back in the day.

I will respect your decision and your method, even if I don't like it too much.
