### ISSUE TITLE
No way to populate a "source" field?

### ISSUE THREAD

**Issue by hengisme3** [rsnitsch/py3createtorrent#2]
Your tool is great but it's really lacking this

**Comment by rsnitsch** [comment]
It is already implemented in the develop branch. I just had no time yet to release a new version.

Link: https://github.com/rsnitsch/py3createtorrent/pull/1

**Comment by rsnitsch** [comment]
Version 0.9.7 with new `--source` parameter has now been released:
https://github.com/rsnitsch/py3createtorrent/releases/tag/v0.9.7
