### ISSUE TITLE
Trackerless torrent

### ISSUE THREAD

**Issue by sergeevabc** [rsnitsch/py3createtorrent#3]
How do I create one?
It’s a requirement of some site which modifies created .torrent later by own means.

**Comment by rsnitsch** [comment]
This is currently not supported by py3createtorrent.

And for the time being I have no time to implement this. But I will keep this issue open so it will be on my TODO list.

**Comment by rsnitsch** [comment]
@sergeevabc I am currently implementing this. If you like you can test it by downloading the current version from the develop branch (unstable): https://github.com/rsnitsch/py3createtorrent/archive/develop.zip

In this version, specifying trackers is optional with the `-t` commandline switch. See: https://py3createtorrent.readthedocs.io/en/develop/user.html#specifying-trackers-t-tracker. And if you don't specify any tracker, it will create a trackerless torrent.

You can optionally provide bootstrap DHT nodes with `--node`, but I don't know if that's necessary in practice. Maybe a trackerless torrent works without bootstrap DHT nodes, maybe not. It probably depends on the client. I have not tested it. Feedback is highly welcome.

**Comment by rsnitsch** [comment]
The requested feature has been implemented, therefore closing this issue.
