### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by nitschis** [rsnitsch/py3createtorrent#33]
This filename causes a crash, I renamed the file but still wanted to report:

'Chemie (1983)(Gerd K'$'\366''nig).sna'

Traceback (most recent call last):
  File "/usr/local/bin/py3createtorrent", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/py3createtorrent.py", line 913, in main
    info = create_multi_file_info(input_path, torrent_files, piece_length, args.include_md5, threads=args.threads)
  File "/usr/local/lib/python3.9/dist-packages/py3createtorrent.py", line 255, in create_multi_file_info
    printv("Processing file '%s'... " % os.path.relpath(path, directory), end="")
  File "/usr/local/lib/python3.9/dist-packages/py3createtorrent.py", line 125, in printv
    print(*args, **kwargs)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf6' in position 106: surrogates not allowed

**Comment by rsnitsch** [comment]
Thank you for reporting. What type of filesystem are you using?

**Comment by MarcoMue** [comment]
I had the Issue using Win 10 with a btfs network Drive.

**Comment by MarcoMue** [comment]
https://cdn.discordapp.com/attachments/446156137952182282/1206766734472912998/image.png?ex=65dd341a&is=65cabf1a&hm=1d06e796d7ecdca422f2c04c44384eefe6021fe4d67abe9c22949306098c8e80&

This is what happens in my script.

**Comment by nitschis** [comment]
Sorry for the late reply. I can not test this anymore. But to answer your question, I was using ext4 on a Debian 12 installation.

Thank you for your work.

**Comment by rsnitsch** [comment]
I will close this now because I assume the fix works.
