### ISSUE TITLE
Where is the config file?

### ISSUE THREAD

**Issue by yesimanoob** [rsnitsch/py3createtorrent#5]
The docs (https://github.com/rsnitsch/py3createtorrent) say there is a small config "at the top" but it doesn't say where to find this file.

Installed via pip on linux.

**Comment by rsnitsch** [comment]
You raised a good question. Before switching to pip, users had to install py3createtorrent locally by extracting it somewhere on their system. Thus, they always knew where the main script file was located.

With pip install, this has become more a little bit difficult. You can locate the directory where py3createtorrent has been installed via pip by executing:

    pip show py3createtorrent

In this directory, you will find the py3createtorrent.py. At the top of this file, you will find the config section.

Of course, any changes you make to this file will be overwritten once you update py3createtorrent via pip. Therefore, for the final release of version 1.0 it is planned to read the config from a dedicated file that can be placed in the user's directory.

**Comment by yesimanoob** [comment]
Yes, having an external config would be great.

In the mean time, I think clarifying where to find the settings would be helpful. Specifically, I think there is issue with the current wording. So, rather than "you can find the configs at a section in the top" it should say what top it's referring to: the main scrip that is installed via PIP. For a while I thought it meant the the top of a config file which I was unable to locate. :(

**Comment by rsnitsch** [comment]
Good point. I updated the docs and hope it is less confusing now: https://py3createtorrent.readthedocs.io/en/develop/user.html#configuration

Also hope that I can finish 1.0 soon so this mess will be fixed.

**Comment by rsnitsch** [comment]
I just released version 1.0.0b1 (beta). The config is now loaded from an external JSON file.
