### ISSUE TITLE
Requires Python 3.8

### ISSUE THREAD

**Issue by dancek** [rsnitsch/py3createtorrent#58]
The software crashes on Python 3.7 and older with the error

```
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)
```

Documentation and `setup.py` should be updated to reflect the actual version requirement.

**Comment by dancek** [comment]
This affects 1.2.*, while 1.1.0 still works on older python versions.

**Comment by rsnitsch** [comment]
Please try again with latest version 1.2.1 (just released).
