### ISSUE TITLE
How to optimize size for torrents?

### ISSUE THREAD

**Issue by Bearmancer** [rsnitsch/py3createtorrent#64]
On some sites there is a limit put upon a torrent that can be uploaded. In my case, I created a torrent for an 18GB video file which exceeded the 2MB cap. How would I make the torrent smaller? I don't have this issue when creating through qBittorrent.

**Comment by rsnitsch** [comment]
18 GB of data should not result in a torrent file exceeding 2 megabytes.

What version of py3createtorrent are you using? When executing py3createtorrent, do you specify a piece size manually with the `-p` option?

**Comment by Bearmancer** [comment]
I fixed it by setting size to 512 bytes for each piece.
