### ISSUE TITLE
Error with path exceeded than 260 characters in Windows

### ISSUE THREAD

**Issue by poonnawit** [rsnitsch/py3createtorrent#9]
I cannot create some torrent that have too long path in directory. Is it about with MAX_PATH?

![py3createtorrent_max_path](https://user-images.githubusercontent.com/29587383/109174293-4bd67b00-77b7-11eb-81eb-4f036b0e594a.PNG)

I tried to enable long path registry with this [link](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later) but it can't solved.

PS: I'm currently using it in Windows 10, I don't know about this problem in Linux.

**Comment by rsnitsch** [comment]
If I recall correctly, the Python installer has an option to remove the MAX_PATH restriction. Try to rerun the Python installer and look for that option.

**Comment by poonnawit** [comment]
Thanks. I have reinstall and tick that option. it's solved.
